"""Offer comments on AGENT-created tasks (задача 1300 + владелец 2026-07-11).

Every task the agent creates (one-off tool + the recurring scheduler) immediately gets a
comment from the most suitable agent: a personal address («Артур, могу помочь выполнить и
закрыть вам эту задачу…») plus a context-specific continuation — a direct offer for a simple
operational task, or a short step plan for a complex one. The responsible replies right in
the comments («да» / «нет») WITHOUT naming the agent — b24bot's mention handler falls back to
the open offer for that task and routes the reply to the offering agent.

Design constraints (owner: «надстройка небольшая, аккуратно и бесшовно»):
  - the offer text is generated by Groq (the same account the OCR path uses) — zero cost to
    the Codex limits; on any Groq failure a fixed honest fallback text is used;
  - the offer is posted ONLY when the task's responsible has access to at least one agent;
    domain routing (юрист/финансист/…) picks among the agents that person can actually use;
  - everything is best-effort in a background thread: a failure here can never break task
    creation; kill-switch B24_TASK_OFFER=0.

Tasks created by PEOPLE are intentionally NOT touched (владелец: «пока думаем»).
"""
from __future__ import annotations

import json
import logging
import os
import re
import threading
from typing import Any

# Engine: 'codex' = a light hermes -z turn (gpt-5.5 — the owner wants real, practical
# recommendations with proper formatting), 'groq' = the free fallback model. The chain is
# codex → groq → fixed text, so an offer is always posted even when both LLMs are down.
_OFFER_ENGINE = os.getenv("B24_OFFER_ENGINE", "codex").strip().lower()
_CODEX_TIMEOUT_S = int(os.getenv("B24_OFFER_CODEX_TIMEOUT_S", "150"))
# llama-3.3-70b writes clean Russian; scout (the OCR model) leaked CJK glyphs into offer texts.
_OFFER_MODEL = os.getenv("B24_OFFER_MODEL", "llama-3.3-70b-versatile")
_OFFER_MAX_CHARS = 1100
# Any CJK leakage means the generation went off the rails — use the honest fallback instead.
_CJK_RE = re.compile(r"[一-鿿぀-ヿ가-힯]")
# Offers are background niceties: never run two hermes subprocesses for them at once
# (2 GB box; Monday 09:00 can create several recurring instances back to back).
_CODEX_GATE = threading.Semaphore(1)
# A short pure-«нет» reply closes the offer without an LLM turn.
_DECLINE_RE = re.compile(r"^(нет|не надо|не нужно|не стоит|сам[аи]?|спасибо,? не надо|нет,? спасибо)[.!)\s]*$",
                         re.IGNORECASE)


def offers_enabled() -> bool:
    return os.getenv("B24_TASK_OFFER", "1").strip() != "0"


def is_decline(text: str) -> bool:
    return bool(_DECLINE_RE.match((text or "").strip().lower()))


# --- candidate agents (access-filtered) -------------------------------------------------------

def _candidate_agents(responsible_id: int) -> list[dict[str, Any]]:
    """Agents the responsible person can actually talk to: main (if allowed) + active subagents
    with a Bitrix bot whose member list admits the person. Each: slug|None(main), name, bot_id,
    role (short specialization text for the router)."""
    import b24bot
    from app import pg_connect
    out: list[dict[str, Any]] = []
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT slug, name, position, role_prompt, bitrix_bot_id FROM agents "
                            "WHERE is_active")
                rows = [dict(r) for r in cur.fetchall()]
    except Exception:  # noqa: BLE001
        logging.warning("task offers: agents load failed", exc_info=True)
        rows = []
    main_bot = None
    try:
        main_bot = b24bot.to_int(b24bot._b24_load_state().get("bot_id"))
    except Exception:  # noqa: BLE001
        pass
    for r in rows:
        role = " ".join(filter(None, [str(r.get("position") or ""),
                                      str(r.get("role_prompt") or "")[:200]])).strip()
        if r["slug"] == "main":
            if b24bot._b24_main_allows(responsible_id):
                out.append({"slug": None, "name": "Агент Албери", "bot_id": main_bot,
                            "role": role or "универсальный агент компании", "is_main": True})
        elif r.get("bitrix_bot_id"):
            if b24bot._b24_task_subagent_allows(r["slug"], responsible_id):
                out.append({"slug": r["slug"], "name": str(r.get("name") or r["slug"]),
                            "bot_id": b24bot.to_int(r["bitrix_bot_id"]), "role": role,
                            "is_main": False})
    return out


# --- offer text (Groq; honest fixed fallback) --------------------------------------------------

def _groq_chat(prompt: str) -> str:
    import urllib.request
    from b24bot import _b24_groq_api_key
    key = _b24_groq_api_key()
    if not key:
        return ""
    payload = {
        "model": _OFFER_MODEL, "max_tokens": 700, "temperature": 0.3,
        "response_format": {"type": "json_object"},
        "messages": [{"role": "user", "content": prompt}],
    }
    req = urllib.request.Request(
        "https://api.groq.com/openai/v1/chat/completions",
        data=json.dumps(payload).encode(),
        headers={"Authorization": "Bearer " + key, "Content-Type": "application/json",
                 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"})
    with urllib.request.urlopen(req, timeout=45) as r:
        d = json.loads(r.read().decode("utf-8", "ignore"))
    return ((d.get("choices") or [{}])[0].get("message", {}) or {}).get("content", "").strip()


def _codex_chat(prompt: str) -> str:
    """One light hermes -z turn (gpt-5.5): the prompt is self-contained, only the tiny built-in
    web toolset rides along so the turn stays cheap. Serialized by a semaphore (2 GB box)."""
    import subprocess
    from b24bot import _hermes_answer_is_error
    with _CODEX_GATE:
        proc = subprocess.run(
            ["hermes", "-z", prompt, "-t", "web", "--yolo"],
            capture_output=True, text=True, timeout=_CODEX_TIMEOUT_S,
            cwd="/root", env={**os.environ, "HOME": "/root"},
        )
    answer = (proc.stdout or "").strip()
    if proc.returncode != 0 or not answer or _hermes_answer_is_error(answer):
        raise RuntimeError(f"hermes rc={proc.returncode} answer={answer[:120]}")
    return answer


def _extract_json(raw: str) -> dict[str, Any]:
    """The model may wrap the JSON in a code fence or prepend a sentence — cut the outer braces."""
    s = (raw or "").strip()
    start, end = s.find("{"), s.rfind("}")
    if start < 0 or end <= start:
        return {}
    try:
        data = json.loads(s[start:end + 1])
        return data if isinstance(data, dict) else {}
    except Exception:  # noqa: BLE001
        return {}


# The agent's HONEST capability inventory — the offer writer must ground every promise in this
# and never invent abilities (owner 2026-07-12: «уточни, что реально умеешь»). Kept accurate to
# the real MCP toolset; when the tools change, update this so offers don't over-promise.
_AGENT_CAPABILITIES = (
    "ЧТО АГЕНТ РЕАЛЬНО УМЕЕТ (предлагай ТОЛЬКО это, точными словами):\n"
    "— Задачи Bitrix: ставить/менять/закрывать задачи и подзадачи, писать комментарии от лица "
    "человека, вести чек-листы, ставить задачи исполнителям со сроками.\n"
    "— Читать и анализировать ВЛОЖЕНИЯ и СКРИНЫ в задаче: распознаёт текст с картинок (OCR), "
    "достаёт текст из PDF/Word/Excel → даёт разбор, вердикт, сводку по их содержимому.\n"
    "— Созвоны: ТОЛЬКО как ТЕКСТОВЫЙ ТРАНСКРИПТ созвона, который УЖЕ записан и синхронизирован в "
    "нашей системе (найти созвон по дате/названию, прочитать транскрипт, собрать выжимку/задачи). "
    "ВИДЕО И АУДИО АГЕНТ НЕ СМОТРИТ И НЕ СЛУШАЕТ — только готовый транскрипт из системы.\n"
    "— CRM: смотреть/создавать/менять воронки, стадии и сделки в Bitrix — собрать воронку по "
    "ОПИСАНИЮ словами или СКРИНУ стадий.\n"
    "— Google-таблицы и документы Word: создать, заполнить, посчитать, оформить.\n"
    "— База знаний компании и интернет: найти информацию, прочитать страницу или файл по ссылке.\n"
    "— Регулярные задачи и автоматизации по расписанию.\n"
    "ЧЕГО АГЕНТ НЕ УМЕЕТ (НИКОГДА не предлагай и не проси для этого материалы):\n"
    "— Смотреть/слушать видео и аудио, работать с записью встречи как с видео (только транскрипт "
    "из системы, если созвон туда записан).\n"
    "— Платить, переводить деньги, физически замерять/отгружать/возить/звонить.\n"
    "— Заходить во внешние системы без доступа (старый портал, чужой аккаунт, банк).\n"
    "— Принимать решения за руководителя."
)


def _task_context(task_id: Any) -> dict[str, Any]:
    """What the task ALREADY contains: checklist, comments and attachments. Read from the indexed
    task JSON (comments arrive there via OnTaskCommentAdd) — free, no OCR. Without this the offer
    asks for material that is already attached, which destroys trust in the agent."""
    ctx: dict[str, Any] = {"checklist": [], "comments": [], "attach_count": 0, "task_files": 0}
    try:
        tid = int(task_id)
    except (TypeError, ValueError):
        return ctx
    import b24bot
    from app import pg_connect
    names = {}
    try:
        names = b24bot._b24_portal_user_directory()
    except Exception:  # noqa: BLE001
        pass
    bot_ids = set()
    try:
        bot_ids = {b24bot.to_int(x) for x in (b24bot._b24_task_bot_author_ids() or set())}
    except Exception:  # noqa: BLE001
        pass
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT raw_json->'comments'->'items' AS items, raw_json->'files' AS files"
                    " FROM bitrix_tasks WHERE bitrix_task_id = %s", (tid,))
                row = cur.fetchone()
    except Exception:  # noqa: BLE001
        logging.warning("task offers: context read failed task=%s", tid, exc_info=True)
        return ctx
    if not row:
        return ctx
    files = row.get("files") or []
    ctx["task_files"] = len(files) if isinstance(files, list) else 0
    for item in (row.get("items") or []):
        if not isinstance(item, dict):
            continue
        author = b24bot.to_int(item.get("author_id"))
        if author in bot_ids:
            continue  # our own offer / replies are not "what the employee already provided"
        params = item.get("params") or {}
        has_file = bool(params.get("FILE_ID") or params.get("FILE_ID[]"))
        text = re.sub(r"\[[^\]]{1,40}\]", " ", str(item.get("text") or "")).strip()
        if has_file:
            ctx["attach_count"] += 1
        if not text and not has_file:
            continue
        ctx["comments"].append({
            "author": names.get(author, {}).get("name") or f"id {author}",
            "text": text[:300],
            "has_file": has_file,
        })
    try:
        from mcp.context_server import _webhook_raw
        r = _webhook_raw("task.checklistitem.getlist", {"taskId": tid})
        for it in (r.get("result") or []):
            t = str((it.get("TITLE") if isinstance(it, dict) else "") or "").strip()
            if t:
                ctx["checklist"].append(t)
    except Exception:  # noqa: BLE001
        logging.debug("task offers: checklist read failed task=%s", tid, exc_info=True)
    return ctx


def _context_block(task: dict[str, Any]) -> str:
    """Render «что УЖЕ есть в задаче» for the offer prompt."""
    lines = []
    desc = str(task.get("description") or "").strip()
    if desc:
        lines.append("ОПИСАНИЕ ЗАДАЧИ (читай целиком, там уже могут быть все данные):\n" + desc[:4000])
    cl = task.get("checklist") or []
    if cl:
        lines.append("ЧЕК-ЛИСТ:\n" + "\n".join(
            f"{i}. {str(c.get('title') if isinstance(c, dict) else c)}" for i, c in enumerate(cl[:20], 1)))
    comments = task.get("comments") or []
    attach = int(task.get("attach_count") or 0)
    if comments or attach:
        head = f"КОММЕНТАРИИ В ЗАДАЧЕ: {len(comments)}"
        if attach:
            head += f", из них С ВЛОЖЕНИЯМИ (скрины/файлы): {attach}"
        rows = []
        for c in comments[:12]:
            body = c.get("text") or ""
            tag = " 📎[вложение приложено]" if c.get("has_file") else ""
            rows.append(f"— {c.get('author')}:{tag} {body}".rstrip())
        lines.append(head + "\n" + "\n".join(rows))
    if int(task.get("task_files") or 0):
        lines.append(f"ФАЙЛЫ, ПРИКРЕПЛЁННЫЕ К САМОЙ ЗАДАЧЕ: {task['task_files']}")
    return "\n\n".join(lines) if lines else "(в задаче только название)"


def _offer_prompt(task: dict[str, Any], candidates: list[dict[str, Any]],
                  responsible_name: str, first_name: str) -> str:
    agents_desc = "\n".join(
        f"- {c['slug'] or 'main'}: «{c['name']}» — {c['role'] or 'универсальный'}" for c in candidates)
    return (
        "Ты — корпоративный ИИ-агент. Пишешь ПЕРВЫЙ комментарий в задаче Bitrix24: коротко и "
        "конкретно предлагаешь СДЕЛАТЬ САМУЮ ТЯЖЁЛУЮ, СОДЕРЖАТЕЛЬНУЮ часть этой задачи за человека — "
        "так, чтобы это реально сэкономило ему время и повысило эффективность. Ничего не вызывай, "
        "просто напиши текст. Ответь СТРОГО одним JSON: "
        "{\"agent\": \"<slug или main>\", \"message\": \"<текст>\"}.\n\n"
        "Агенты (выбери профильного под тему; сомневаешься — main):\n" + agents_desc + "\n\n"
        + _AGENT_CAPABILITIES + "\n\n"
        "ЗАДАЧА №" + str(task.get("id") or "") + "\nНазвание: " + str(task.get("title") or "") + "\n"
        "Ответственный: " + (responsible_name or "сотрудник") + "\n\n"
        "=== ЧТО УЖЕ ЕСТЬ В ЗАДАЧЕ ===\n" + _context_block(task) + "\n"
        "=== КОНЕЦ СОДЕРЖИМОГО ЗАДАЧИ ===\n\n"
        "🚫 ГЛАВНЫЙ ЗАПРЕТ — НЕ ПРОСИ ТО, ЧТО УЖЕ ЕСТЬ. Сначала ВНИМАТЕЛЬНО прочитай описание, "
        "чек-лист и комментарии выше. Если данные/файлы/скрины уже приложены или уже написаны в "
        "описании — НЕЛЬЗЯ просить прислать их снова: это выглядит глупо и подрывает доверие. "
        "Вместо запроса — сразу предложи СДЕЛАТЬ РАБОТУ по тому, что уже есть, и назови это "
        "конкретно («вижу 12 приложенных скринов отзывов — разберу все и дам сводку претензий», "
        "«в описании уже есть полный свод по руководителям — подготовлю по нему адресные "
        "рекомендации»). Просить материалы можно ТОЛЬКО если в задаче их действительно нет.\n\n"
        "ГЛАВНОЕ ПРАВИЛО: предлагай РЕЗУЛЬТАТ, а не «навести порядок». Найди в задаче самое "
        "трудоёмкое действие, которое агент РЕАЛЬНО умеет из списка выше, и предложи выполнить "
        "именно его. СВЕРЬСЯ со списком возможностей ПЕРЕД тем, как что-то обещать: если действие "
        "требует того, чего агент НЕ умеет (видео/аудио, оплата, чужая система) — НЕ предлагай это "
        "и не проси для этого материалы; предложи только ту часть, что реально в его силах, а если "
        "по сути задачи агент не может ничего полезного — верни пустой message (\"\").\n"
        "Примеры хорошего оффера: негативные отзывы → «скиньте скрины отзывов — разберу и дам "
        "вердикт: суть претензий, что критично, что ответить»; воронка → «опишите стадии или "
        "скиньте скрин — соберу такую же в Bitrix»; выжимка по созвону → ТОЛЬКО если созвон записан "
        "в нашей системе: «подскажите дату/название созвона — найду его транскрипт в системе и "
        "соберу выжимку и задачи» (НЕ проси прислать видеозапись).\n"
        "ЗАПРЕЩЕНО (плохие, пустые рекомендации): «подготовить структуру/шаблон/реестр/чек-лист», "
        "«навести порядок», «оформить сводку по этапам», сделать таблицу для того, что человек и так "
        "ведёт своим способом. Не предлагай процесс — предлагай сделать саму работу.\n\n"
        "ФОРМАТ message (по-русски, коротко, до 700 символов, Bitrix BB-код, НЕ Markdown):\n"
        "1) «" + (first_name or "Коллега") + ", ...» — по имени, по-человечески.\n"
        "2) 1-2 предложения или 2-3 пункта «— » с КОНКРЕТНЫМ действием и его эффектом; ключевое "
        "[b]жирным[/b].\n"
        "3) Если материалов ДОСТАТОЧНО (они уже в описании/чек-листе/комментариях/вложениях) — "
        "НЕ задавай вопросов вообще: просто скажи, что готов взяться и что именно сделаешь по "
        "имеющимся данным. Вопрос задавай ТОЛЬКО когда для работы реально не хватает входных "
        "данных, и проси то, что человеку легко дать (скрин, описание словами, ссылку). НЕ проси "
        "доступ к чужим/внешним системам.\n"
        "4) НЕ зови отвечать «прямо здесь» и не проси писать тебе в комментариях: финальную "
        "строку о том, как тебя позвать через @, система добавит сама.\n"
        "Если по сути задачи агент реально ничем помочь не может — верни пустой message (\"\"), "
        "не выдумывай пользу. Ничего не обещай, чего агент сделать не может."
    )


def compose_offer(task: dict[str, Any], candidates: list[dict[str, Any]],
                  responsible_name: str) -> tuple[dict[str, Any], str]:
    """Pick the best-suited agent and write the offer text. Returns (agent, message).
    Engine chain: codex (real practical recommendations, proper BB formatting — owner's call
    2026-07-11) → groq → fixed fallback, so an offer is always posted even with both LLMs down."""
    first_name = (responsible_name or "").split()[0] if responsible_name else ""
    fallback_agent = next((c for c in candidates if c.get("is_main")), candidates[0])
    fallback_msg = ((first_name + ", ") if first_name else "") + (
        "могу помочь выполнить и закрыть вам эту задачу — я вижу её контекст.")
    if len(candidates) == 1 and not (task.get("title") or task.get("description")):
        return fallback_agent, fallback_msg
    prompt = _offer_prompt(task, candidates, responsible_name, first_name)
    engines = ("codex", "groq") if _OFFER_ENGINE != "groq" else ("groq",)
    for engine in engines:
        try:
            raw = _codex_chat(prompt) if engine == "codex" else _groq_chat(prompt)
            data = _extract_json(raw)
            msg = str(data.get("message") or "").strip()[:_OFFER_MAX_CHARS]
            slug = str(data.get("agent") or "main").strip()
            agent = next((c for c in candidates if (c["slug"] or "main") == slug), fallback_agent)
            if msg and not _CJK_RE.search(msg):
                return agent, msg
            logging.warning("task offers: %s compose returned unusable text", engine)
        except Exception as exc:  # noqa: BLE001
            logging.warning("task offers: %s compose failed: %s", engine, repr(exc)[:160])
    return fallback_agent, fallback_msg


# --- storage -----------------------------------------------------------------------------------

def _save_offer(task_id: int, agent: dict[str, Any], responsible_id: int,
                creator_id: int | None) -> None:
    from app import pg_connect
    with pg_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO bitrix_task_agent_offers (task_id, agent_slug, agent_name, bot_id, "
                "responsible_id, creator_id, state) VALUES (%s,%s,%s,%s,%s,%s,'open') "
                "ON CONFLICT (task_id) DO UPDATE SET agent_slug=EXCLUDED.agent_slug, "
                "agent_name=EXCLUDED.agent_name, bot_id=EXCLUDED.bot_id, state='open', "
                "updated_at=now()",
                (int(task_id), agent.get("slug"), agent.get("name"), agent.get("bot_id"),
                 int(responsible_id), creator_id))


def open_offer_for(task_id: int, author_id: int) -> dict[str, Any] | None:
    """The open offer of this task IF the comment author is its responsible or creator —
    that's who the offer addressed, so their reply goes to the offering agent."""
    from app import pg_connect
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT task_id, agent_slug, agent_name, bot_id, responsible_id, "
                            "creator_id, state FROM bitrix_task_agent_offers "
                            "WHERE task_id = %s AND state = 'open'", (int(task_id),))
                row = cur.fetchone()
    except Exception:  # noqa: BLE001
        logging.warning("task offers: lookup failed task=%s", task_id, exc_info=True)
        return None
    if not row:
        return None
    row = dict(row)
    if int(author_id or 0) not in {int(row.get("responsible_id") or 0), int(row.get("creator_id") or 0)}:
        return None
    return row


def mark_declined(task_id: int) -> None:
    from app import pg_connect
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("UPDATE bitrix_task_agent_offers SET state='declined', updated_at=now() "
                            "WHERE task_id = %s", (int(task_id),))
    except Exception:  # noqa: BLE001
        logging.warning("task offers: decline mark failed task=%s", task_id, exc_info=True)


# --- entry point (fired after the agent created a task) ---------------------------------------

def _summon_tail(agent: dict[str, Any]) -> str:
    """Fixed closing line of every offer: HOW to summon the agent. Appended in code — not by
    the LLM — so the «отвечаю только когда позвали через @» rule reads the same in every task.
    Agents no longer react to unaddressed comments (owner's decision 2026-07-13)."""
    name = str(agent.get("name") or "Агент Албери").strip()
    short = "Албери" if agent.get("is_main") or not agent.get("slug") else name
    return (
        "\n\n[b]Нужна помощь — позовите меня через @.[/b] В комментарии введите символ @, начните "
        "печатать «" + name + "» и выберите меня в подсказке (можно и просто написать «" + short +
        "»), затем добавьте, что сделать. Пример: «@" + name + " возьми это на себя». "
        "Пока меня не позвали по имени — я в вашу переписку не вмешиваюсь."
    )


def _post_offer(task_id: int, title: str, description: str, checklist: Any,
                responsible_id: int, creator_id: int | None) -> None:
    import b24bot
    candidates = _candidate_agents(responsible_id)
    if not candidates:
        logging.info("task offers: %s — responsible %s has no agent access, skipping",
                     task_id, responsible_id)
        return
    directory = b24bot._b24_portal_user_directory()
    responsible_name = directory.get(int(responsible_id), {}).get("name") or ""
    # The offer must be written against the WHOLE task — description, checklist, comments and the
    # attachments already there. Without this it asks for material the employee already provided
    # (2026-07-14: task 962 had 12 screenshots attached and the offer still asked for screenshots).
    ctx = _task_context(task_id)
    task_ctx = {
        "id": task_id,
        "title": title,
        "description": description,
        "checklist": checklist or ctx["checklist"],
        "comments": ctx["comments"],
        "attach_count": ctx["attach_count"],
        "task_files": ctx["task_files"],
    }
    agent, message = compose_offer(task_ctx, candidates, responsible_name)
    message = message.rstrip() + _summon_tail(agent)
    posted = b24bot._b24_post_task_comment(int(task_id), message, agent["name"], agent.get("bot_id"))
    if posted:
        _save_offer(task_id, agent, responsible_id, creator_id)
        logging.info("task offers: posted on task %s as %s", task_id, agent["name"])
    else:
        logging.warning("task offers: post failed task=%s", task_id)


def schedule_offer(task_id: Any, *, title: str = "", description: str = "", checklist: Any = None,
                   responsible_id: Any = None, creator_id: Any = None) -> None:
    """Fire-and-forget: never blocks or fails task creation. Called right after the agent
    created a Bitrix task (one-off tool and the recurring scheduler)."""
    if not offers_enabled():
        return
    try:
        tid = int(task_id)
        rid = int(responsible_id)
    except (TypeError, ValueError):
        return
    try:
        cid = int(creator_id) if creator_id not in (None, "") else None
    except (TypeError, ValueError):
        cid = None

    def _run() -> None:
        try:
            _post_offer(tid, str(title or ""), str(description or ""), checklist, rid, cid)
        except Exception:  # noqa: BLE001
            logging.warning("task offers: offer thread failed task=%s", tid, exc_info=True)

    threading.Thread(target=_run, daemon=True, name=f"task-offer-{tid}").start()
