"""Offer comments on AGENT-created tasks (задача 1300 + владелец 2026-07-11).

Every task the agent creates (one-off tool + the recurring scheduler) immediately gets a
comment from the most suitable agent: a personal address («Артур, могу помочь выполнить и
закрыть вам эту задачу…») plus a context-specific continuation — a direct offer for a simple
operational task, or a short step plan for a complex one. The responsible replies right in
the comments («да» / «нет») WITHOUT naming the agent — b24bot's mention handler falls back to
the open offer for that task and routes the reply to the offering agent.

Design constraints (owner: «надстройка небольшая, аккуратно и бесшовно»):
  - the offer text is generated by Groq (the same account the OCR path uses) — zero cost to
    the Codex limits; on any Groq failure a fixed honest fallback text is used;
  - the offer is posted ONLY when the task's responsible has access to at least one agent;
    domain routing (юрист/финансист/…) picks among the agents that person can actually use;
  - everything is best-effort in a background thread: a failure here can never break task
    creation; kill-switch B24_TASK_OFFER=0.

Tasks created by PEOPLE are intentionally NOT touched (владелец: «пока думаем»).
"""
from __future__ import annotations

import json
import logging
import os
import re
import threading
from typing import Any

_OFFER_MODEL = os.getenv("B24_OFFER_MODEL", "meta-llama/llama-4-scout-17b-16e-instruct")
_OFFER_MAX_CHARS = 900
# A short pure-«нет» reply closes the offer without an LLM turn.
_DECLINE_RE = re.compile(r"^(нет|не надо|не нужно|не стоит|сам[аи]?|спасибо,? не надо|нет,? спасибо)[.!)\s]*$",
                         re.IGNORECASE)


def offers_enabled() -> bool:
    return os.getenv("B24_TASK_OFFER", "1").strip() != "0"


def is_decline(text: str) -> bool:
    return bool(_DECLINE_RE.match((text or "").strip().lower()))


# --- candidate agents (access-filtered) -------------------------------------------------------

def _candidate_agents(responsible_id: int) -> list[dict[str, Any]]:
    """Agents the responsible person can actually talk to: main (if allowed) + active subagents
    with a Bitrix bot whose member list admits the person. Each: slug|None(main), name, bot_id,
    role (short specialization text for the router)."""
    import b24bot
    from app import pg_connect
    out: list[dict[str, Any]] = []
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT slug, name, position, role_prompt, bitrix_bot_id FROM agents "
                            "WHERE is_active")
                rows = [dict(r) for r in cur.fetchall()]
    except Exception:  # noqa: BLE001
        logging.warning("task offers: agents load failed", exc_info=True)
        rows = []
    main_bot = None
    try:
        main_bot = b24bot.to_int(b24bot._b24_load_state().get("bot_id"))
    except Exception:  # noqa: BLE001
        pass
    for r in rows:
        role = " ".join(filter(None, [str(r.get("position") or ""),
                                      str(r.get("role_prompt") or "")[:200]])).strip()
        if r["slug"] == "main":
            if b24bot._b24_main_allows(responsible_id):
                out.append({"slug": None, "name": "Агент Албери", "bot_id": main_bot,
                            "role": role or "универсальный агент компании", "is_main": True})
        elif r.get("bitrix_bot_id"):
            if b24bot._b24_task_subagent_allows(r["slug"], responsible_id):
                out.append({"slug": r["slug"], "name": str(r.get("name") or r["slug"]),
                            "bot_id": b24bot.to_int(r["bitrix_bot_id"]), "role": role,
                            "is_main": False})
    return out


# --- offer text (Groq; honest fixed fallback) --------------------------------------------------

def _groq_chat(prompt: str) -> str:
    import urllib.request
    from b24bot import _b24_groq_api_key
    key = _b24_groq_api_key()
    if not key:
        return ""
    payload = {
        "model": _OFFER_MODEL, "max_tokens": 700, "temperature": 0.3,
        "response_format": {"type": "json_object"},
        "messages": [{"role": "user", "content": prompt}],
    }
    req = urllib.request.Request(
        "https://api.groq.com/openai/v1/chat/completions",
        data=json.dumps(payload).encode(),
        headers={"Authorization": "Bearer " + key, "Content-Type": "application/json",
                 "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"})
    with urllib.request.urlopen(req, timeout=45) as r:
        d = json.loads(r.read().decode("utf-8", "ignore"))
    return ((d.get("choices") or [{}])[0].get("message", {}) or {}).get("content", "").strip()


def compose_offer(task: dict[str, Any], candidates: list[dict[str, Any]],
                  responsible_name: str) -> tuple[dict[str, Any], str]:
    """Pick the best-suited agent and write the offer text. Returns (agent, message).
    Groq does both in one call; any failure degrades to (main-or-first, fixed text)."""
    first_name = (responsible_name or "").split()[0] if responsible_name else ""
    fallback_agent = next((c for c in candidates if c.get("is_main")), candidates[0])
    fallback_msg = ((first_name + ", ") if first_name else "") + (
        "могу помочь выполнить и закрыть вам эту задачу. Напишите прямо здесь, с чего начать, "
        "или просто «да» — и я возьмусь. Я вижу контекст задачи.")
    if len(candidates) == 1 and not (task.get("title") or task.get("description")):
        return fallback_agent, fallback_msg
    agents_desc = "\n".join(
        f"- {c['slug'] or 'main'}: «{c['name']}» — {c['role'] or 'универсальный'}" for c in candidates)
    checklist = task.get("checklist") or []
    cl_txt = "\n".join(f"{i}. {str(it.get('title') if isinstance(it, dict) else it)}"
                       for i, it in enumerate(checklist[:15], 1))
    prompt = (
        "Ты подбираешь ИИ-агента и пишешь ПЕРВЫЙ комментарий-предложение помощи в новой задаче "
        "Bitrix24. Верни СТРОГО JSON: {\"agent\": \"<slug или main>\", \"message\": \"<текст>\"}.\n\n"
        "Доступные агенты (выбери самого профильного; сомневаешься — main):\n" + agents_desc + "\n\n"
        "Задача:\nНазвание: " + str(task.get("title") or "") + "\n"
        "Описание: " + str(task.get("description") or "")[:1500] + "\n"
        + (("Чек-лист:\n" + cl_txt + "\n") if cl_txt else "")
        + "Ответственный: " + (responsible_name or "сотрудник") + "\n\n"
        "Требования к message (по-русски, БЕЗ Markdown; жирный только [b]...[/b]; до 700 символов):\n"
        "1) Обратись по имени: «" + (first_name or "Коллега") + ", могу помочь выполнить и закрыть "
        "вам эту задачу.»\n"
        "2) Дальше — ПО СУТИ задачи: если она простая/операционная — задай один конкретный вопрос-"
        "предложение (например «скажите, могу ли я поставить задачи исполнителям?»); если сложная — "
        "предложи короткий план в 3-5 шагов, что сделаем вместе, и спроси, с какого шага начать.\n"
        "3) Закончи фразой: «Ответьте прямо здесь — я увижу ваше сообщение.»\n"
        "Не выдумывай данных, которых нет в задаче; не обещай того, что не следует из её текста."
    )
    try:
        raw = _groq_chat(prompt)
        data = json.loads(raw) if raw else {}
        msg = str(data.get("message") or "").strip()[:_OFFER_MAX_CHARS]
        slug = str(data.get("agent") or "main").strip()
        agent = next((c for c in candidates if (c["slug"] or "main") == slug), fallback_agent)
        if msg:
            return agent, msg
    except Exception as exc:  # noqa: BLE001
        logging.warning("task offers: groq compose failed: %s", repr(exc)[:160])
    return fallback_agent, fallback_msg


# --- storage -----------------------------------------------------------------------------------

def _save_offer(task_id: int, agent: dict[str, Any], responsible_id: int,
                creator_id: int | None) -> None:
    from app import pg_connect
    with pg_connect() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO bitrix_task_agent_offers (task_id, agent_slug, agent_name, bot_id, "
                "responsible_id, creator_id, state) VALUES (%s,%s,%s,%s,%s,%s,'open') "
                "ON CONFLICT (task_id) DO UPDATE SET agent_slug=EXCLUDED.agent_slug, "
                "agent_name=EXCLUDED.agent_name, bot_id=EXCLUDED.bot_id, state='open', "
                "updated_at=now()",
                (int(task_id), agent.get("slug"), agent.get("name"), agent.get("bot_id"),
                 int(responsible_id), creator_id))


def open_offer_for(task_id: int, author_id: int) -> dict[str, Any] | None:
    """The open offer of this task IF the comment author is its responsible or creator —
    that's who the offer addressed, so their reply goes to the offering agent."""
    from app import pg_connect
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT task_id, agent_slug, agent_name, bot_id, responsible_id, "
                            "creator_id, state FROM bitrix_task_agent_offers "
                            "WHERE task_id = %s AND state = 'open'", (int(task_id),))
                row = cur.fetchone()
    except Exception:  # noqa: BLE001
        logging.warning("task offers: lookup failed task=%s", task_id, exc_info=True)
        return None
    if not row:
        return None
    row = dict(row)
    if int(author_id or 0) not in {int(row.get("responsible_id") or 0), int(row.get("creator_id") or 0)}:
        return None
    return row


def mark_declined(task_id: int) -> None:
    from app import pg_connect
    try:
        with pg_connect() as conn:
            with conn.cursor() as cur:
                cur.execute("UPDATE bitrix_task_agent_offers SET state='declined', updated_at=now() "
                            "WHERE task_id = %s", (int(task_id),))
    except Exception:  # noqa: BLE001
        logging.warning("task offers: decline mark failed task=%s", task_id, exc_info=True)


# --- entry point (fired after the agent created a task) ---------------------------------------

def _post_offer(task_id: int, title: str, description: str, checklist: Any,
                responsible_id: int, creator_id: int | None) -> None:
    import b24bot
    candidates = _candidate_agents(responsible_id)
    if not candidates:
        logging.info("task offers: %s — responsible %s has no agent access, skipping",
                     task_id, responsible_id)
        return
    directory = b24bot._b24_portal_user_directory()
    responsible_name = directory.get(int(responsible_id), {}).get("name") or ""
    agent, message = compose_offer(
        {"title": title, "description": description, "checklist": checklist},
        candidates, responsible_name)
    posted = b24bot._b24_post_task_comment(int(task_id), message, agent["name"], agent.get("bot_id"))
    if posted:
        _save_offer(task_id, agent, responsible_id, creator_id)
        logging.info("task offers: posted on task %s as %s", task_id, agent["name"])
    else:
        logging.warning("task offers: post failed task=%s", task_id)


def schedule_offer(task_id: Any, *, title: str = "", description: str = "", checklist: Any = None,
                   responsible_id: Any = None, creator_id: Any = None) -> None:
    """Fire-and-forget: never blocks or fails task creation. Called right after the agent
    created a Bitrix task (one-off tool and the recurring scheduler)."""
    if not offers_enabled():
        return
    try:
        tid = int(task_id)
        rid = int(responsible_id)
    except (TypeError, ValueError):
        return
    try:
        cid = int(creator_id) if creator_id not in (None, "") else None
    except (TypeError, ValueError):
        cid = None

    def _run() -> None:
        try:
            _post_offer(tid, str(title or ""), str(description or ""), checklist, rid, cid)
        except Exception:  # noqa: BLE001
            logging.warning("task offers: offer thread failed task=%s", tid, exc_info=True)

    threading.Thread(target=_run, daemon=True, name=f"task-offer-{tid}").start()
